database:
  url: 'jdbc:postgresql://localhost:5432/uap'
  username: 'uap_user'
  password: 'uap_user'

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

jwt:
  secret: '5166546A576E5A7234743777217A25432A462D4A614E645267556B5870327335'
