### Register a new account

POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "email": "ioseb@amazingjob.com",
  "username": "soso",
  "password": "amazing1234"
}

> {% client.global.set('auth-token', response.body.token); %}

### Log into an existing account

POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "username": "soso",
  "password": "amazing1234"
}

> {% client.global.set('auth-token', response.body.token); %}
