version: '3'
services:
  database:
    image: 'postgres:15-alpine'
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: 'plamogus'
      POSTGRES_USER: 'plamogus_user'
      POSTGRES_PASSWORD: 'plamogus_user'
